### PR TITLE
Added styles v1

### PR DESCRIPTION
**Pull request by PrathameshhW**

### CODE REVIEW

**Comment by PrathameshhW** [comment]
All the options are centred with the help of Flexbox. The final look 
Screenshot 2023-08-17 200302

**Comment by niranjank2022** [comment]
> All the options are centred with the help of Flexbox. The final look Screenshot 2023-08-17 200302

@PrathameshhW 
You have done a great job. The design idea is really amazing. It would be great if some more changes were made.

Firstly, a fix is needed in yours, if we add more than 4 subjects, it ain't possible to go to the heading section. As we add more subjects, we can't reach the subject boxes at the top.
Screenshot (58)
Screenshot (57)

Secondly, I would like the heading GPA calculator to be fixed i.e. it should not change position when new subjects are deleted or existing ones deleted.

Thirdly, can we make the look more pleasing by adding colours to the subject box?
Fourthly, decrease the font size of the Credit and Grade

Thank you!

**Comment by PrathameshhW** [comment]
Sure. We can work on that. I'll send the PR after some time.

**Comment by niranjank2022** [comment]
> Sure. We can work on that. I'll send the PR after some time.

@PrathameshhW 
No need to create a new PR. You can make the changes in the current branch of yours and push it.

**Comment by niranjank2022** [comment]
And also, please mention the issue in the PR description.

**Comment by niranjank2022** [comment]
I'm closing this as you submitted the other PR which also contains these changes.

**Pull request closed without merging**
